//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v8.1.0
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace BOI.Umbraco.Models
{

	public partial class DocumentUploadItem 
	{
        public long DocumentViewedCount { get; set; }
    }
}
