//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder.Embedded v13.4.1+d72fc5c
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Linq.Expressions;
using Umbraco.Cms.Core.Models.PublishedContent;
using Umbraco.Cms.Core.PublishedCache;
using Umbraco.Cms.Infrastructure.ModelsBuilder;
using Umbraco.Cms.Core;
using Umbraco.Extensions;

namespace BOI.Umbraco.Models
{
	/// <summary>Grad Account Rate</summary>
	[PublishedModel("gradAccountRate")]
	public partial class GradAccountRate : PublishedElementModel
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.4.1+d72fc5c")]
		public new const string ModelTypeAlias = "gradAccountRate";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.4.1+d72fc5c")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.4.1+d72fc5c")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public new static IPublishedContentType GetModelContentType(IPublishedSnapshotAccessor publishedSnapshotAccessor)
			=> PublishedModelUtility.GetModelContentType(publishedSnapshotAccessor, ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.4.1+d72fc5c")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(IPublishedSnapshotAccessor publishedSnapshotAccessor, Expression<Func<GradAccountRate, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(publishedSnapshotAccessor), selector);
#pragma warning restore 0109

		private IPublishedValueFallback _publishedValueFallback;

		// ctor
		public GradAccountRate(IPublishedElement content, IPublishedValueFallback publishedValueFallback)
			: base(content, publishedValueFallback)
		{
			_publishedValueFallback = publishedValueFallback;
		}

		// properties

		///<summary>
		/// Arranged Overdraft Rate %
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.4.1+d72fc5c")]
		[ImplementPropertyType("arrangedOverdraftRate")]
		public virtual decimal ArrangedOverdraftRate => this.Value<decimal>(_publishedValueFallback, "arrangedOverdraftRate");

		///<summary>
		/// Arranged Overdraft Rate EAR %
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.4.1+d72fc5c")]
		[ImplementPropertyType("arrangedOverdraftRateEAR")]
		public virtual decimal ArrangedOverdraftRateEar => this.Value<decimal>(_publishedValueFallback, "arrangedOverdraftRateEAR");

		///<summary>
		/// Overdraft Limit: Interest free arranged overdraft limit
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.4.1+d72fc5c")]
		[ImplementPropertyType("overdraftLimit")]
		public virtual decimal OverdraftLimit => this.Value<decimal>(_publishedValueFallback, "overdraftLimit");

		///<summary>
		/// Unarranged Overdraft Rate EAR %: With an Arranged OD
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.4.1+d72fc5c")]
		[ImplementPropertyType("unarrangedOverdraftRateEARWith")]
		public virtual decimal UnarrangedOverdraftRateEarwith => this.Value<decimal>(_publishedValueFallback, "unarrangedOverdraftRateEARWith");

		///<summary>
		/// Unarranged Overdraft Rate EAR %: Without an Arranged OD
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.4.1+d72fc5c")]
		[ImplementPropertyType("unarrangedOverdraftRateEARWithout")]
		public virtual decimal UnarrangedOverdraftRateEarwithout => this.Value<decimal>(_publishedValueFallback, "unarrangedOverdraftRateEARWithout");

		///<summary>
		/// Unarranged Overdraft Rate %: With an Arranged OD
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.4.1+d72fc5c")]
		[ImplementPropertyType("unarrangedOverdraftRateWith")]
		public virtual decimal UnarrangedOverdraftRateWith => this.Value<decimal>(_publishedValueFallback, "unarrangedOverdraftRateWith");

		///<summary>
		/// Unarranged Overdraft Rate %: Without an Arranged OD
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.4.1+d72fc5c")]
		[ImplementPropertyType("unarrangedOverdraftRateWithout")]
		public virtual decimal UnarrangedOverdraftRateWithout => this.Value<decimal>(_publishedValueFallback, "unarrangedOverdraftRateWithout");

		///<summary>
		/// Years of full time 3rd level education: Excluding post-grad years - this is what will appear in the Undergraduate Course dropdown on the Calculator page
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.4.1+d72fc5c")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("yearsOfFullTime3rdLevelEducation")]
		public virtual string YearsOfFullTime3rdLevelEducation => this.Value<string>(_publishedValueFallback, "yearsOfFullTime3rdLevelEducation");
	}
}
