//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder.Embedded v13.8.1+dcbbed4
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Linq.Expressions;
using Umbraco.Cms.Core.Models.PublishedContent;
using Umbraco.Cms.Core.PublishedCache;
using Umbraco.Cms.Infrastructure.ModelsBuilder;
using Umbraco.Cms.Core;
using Umbraco.Extensions;

namespace BOI.Umbraco.Models
{
	/// <summary>Overdraft Calculator</summary>
	[PublishedModel("overdraftCalculator")]
	public partial class OverdraftCalculator : PublishedContentModel, IListingMixin, INavigationMixin, IPageSettingsMixin, ISearchMixin
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.8.1+dcbbed4")]
		public new const string ModelTypeAlias = "overdraftCalculator";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.8.1+dcbbed4")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.8.1+dcbbed4")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public new static IPublishedContentType GetModelContentType(IPublishedSnapshotAccessor publishedSnapshotAccessor)
			=> PublishedModelUtility.GetModelContentType(publishedSnapshotAccessor, ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.8.1+dcbbed4")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(IPublishedSnapshotAccessor publishedSnapshotAccessor, Expression<Func<OverdraftCalculator, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(publishedSnapshotAccessor), selector);
#pragma warning restore 0109

		private IPublishedValueFallback _publishedValueFallback;

		// ctor
		public OverdraftCalculator(IPublishedContent content, IPublishedValueFallback publishedValueFallback)
			: base(content, publishedValueFallback)
		{
			_publishedValueFallback = publishedValueFallback;
		}

		// properties

		///<summary>
		/// Account Type Help Message
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.8.1+dcbbed4")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("accountTypeHelpMessage")]
		public virtual string AccountTypeHelpMessage => this.Value<string>(_publishedValueFallback, "accountTypeHelpMessage");

		///<summary>
		/// Arraged Overdraft Limit Help Message
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.8.1+dcbbed4")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("arragedOverdraftLimitHelpMessage")]
		public virtual string ArragedOverdraftLimitHelpMessage => this.Value<string>(_publishedValueFallback, "arragedOverdraftLimitHelpMessage");

		///<summary>
		/// Arranged Overdraft Interest Rate Help Message
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.8.1+dcbbed4")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("arrangedOverdraftInterestRateHelpMessage")]
		public virtual string ArrangedOverdraftInterestRateHelpMessage => this.Value<string>(_publishedValueFallback, "arrangedOverdraftInterestRateHelpMessage");

		///<summary>
		/// Background Image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.8.1+dcbbed4")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("backgroundImage")]
		public virtual global::Umbraco.Cms.Core.Models.PublishedContent.IPublishedContent BackgroundImage => this.Value<global::Umbraco.Cms.Core.Models.PublishedContent.IPublishedContent>(_publishedValueFallback, "backgroundImage");

		///<summary>
		/// Base Rate: Only used when user manually enters Arranged Overdraft Interest Rate
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.8.1+dcbbed4")]
		[ImplementPropertyType("baseRate")]
		public virtual decimal BaseRate => this.Value<decimal>(_publishedValueFallback, "baseRate");

		///<summary>
		/// Button Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.8.1+dcbbed4")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("buttonText")]
		public virtual string ButtonText => this.Value<string>(_publishedValueFallback, "buttonText");

		///<summary>
		/// Clear Account (NI) Arrange Overdraft Rate %: Only used when user manually enters Arranged Overdraft Interest Rate
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.8.1+dcbbed4")]
		[ImplementPropertyType("clearAccountNIArrangeOverdraftRate")]
		public virtual decimal ClearAccountNiarrangeOverdraftRate => this.Value<decimal>(_publishedValueFallback, "clearAccountNIArrangeOverdraftRate");

		///<summary>
		/// Days in Overdraft Help Message
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.8.1+dcbbed4")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("daysInOverdraftHelpMessage")]
		public virtual string DaysInOverdraftHelpMessage => this.Value<string>(_publishedValueFallback, "daysInOverdraftHelpMessage");

		///<summary>
		/// Disclaimer Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.8.1+dcbbed4")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("disclaimerText")]
		public virtual global::Umbraco.Cms.Core.Strings.IHtmlEncodedString DisclaimerText => this.Value<global::Umbraco.Cms.Core.Strings.IHtmlEncodedString>(_publishedValueFallback, "disclaimerText");

		///<summary>
		/// Grad Account Rates
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.8.1+dcbbed4")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("gradAccountRates")]
		public virtual global::Umbraco.Cms.Core.Models.Blocks.BlockListModel GradAccountRates => this.Value<global::Umbraco.Cms.Core.Models.Blocks.BlockListModel>(_publishedValueFallback, "gradAccountRates");

		///<summary>
		/// Into Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.8.1+dcbbed4")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("introText")]
		public virtual global::Umbraco.Cms.Core.Strings.IHtmlEncodedString IntroText => this.Value<global::Umbraco.Cms.Core.Strings.IHtmlEncodedString>(_publishedValueFallback, "introText");

		///<summary>
		/// Intro Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.8.1+dcbbed4")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("introTitle")]
		public virtual string IntroTitle => this.Value<string>(_publishedValueFallback, "introTitle");

		///<summary>
		/// Length of Undergrad Course Help Message
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.8.1+dcbbed4")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("lengthOfUndergradCourseHelpMessage")]
		public virtual string LengthOfUndergradCourseHelpMessage => this.Value<string>(_publishedValueFallback, "lengthOfUndergradCourseHelpMessage");

		///<summary>
		/// Overdraft Amount Help Message
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.8.1+dcbbed4")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("overdraftAmountHelpMessage")]
		public virtual string OverdraftAmountHelpMessage => this.Value<string>(_publishedValueFallback, "overdraftAmountHelpMessage");

		///<summary>
		/// Overdraft Rates
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.8.1+dcbbed4")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("overdraftRates")]
		public virtual global::Umbraco.Cms.Core.Models.Blocks.BlockListModel OverdraftRates => this.Value<global::Umbraco.Cms.Core.Models.Blocks.BlockListModel>(_publishedValueFallback, "overdraftRates");

		///<summary>
		/// Over Interest Free Limit - Arranged Overdraft Rate %
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.8.1+dcbbed4")]
		[ImplementPropertyType("overInterestFreeLimitArrangedOverdraftRate")]
		public virtual decimal OverInterestFreeLimitArrangedOverdraftRate => this.Value<decimal>(_publishedValueFallback, "overInterestFreeLimitArrangedOverdraftRate");

		///<summary>
		/// Over Interest Free Limit - Arranged Overdraft Rate EAR %
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.8.1+dcbbed4")]
		[ImplementPropertyType("overInterestFreeLimitArrangedOverdraftRateEAR")]
		public virtual decimal OverInterestFreeLimitArrangedOverdraftRateEar => this.Value<decimal>(_publishedValueFallback, "overInterestFreeLimitArrangedOverdraftRateEAR");

		///<summary>
		/// Over Interest Free Limit - Unarranged Overdraft Rate EAR %: With an Arranged OD
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.8.1+dcbbed4")]
		[ImplementPropertyType("overInterestFreeLimitUnarrangedOverdraftRateEARWith")]
		public virtual decimal OverInterestFreeLimitUnarrangedOverdraftRateEarwith => this.Value<decimal>(_publishedValueFallback, "overInterestFreeLimitUnarrangedOverdraftRateEARWith");

		///<summary>
		/// Over Interest Free Limit - Unarranged Overdraft Rate EAR %: Without an Arranged OD
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.8.1+dcbbed4")]
		[ImplementPropertyType("overInterestFreeLimitUnarrangedOverdraftRateEARWithout")]
		public virtual decimal OverInterestFreeLimitUnarrangedOverdraftRateEarwithout => this.Value<decimal>(_publishedValueFallback, "overInterestFreeLimitUnarrangedOverdraftRateEARWithout");

		///<summary>
		/// Over Interest Free Limit - Unarranged Overdraft Rate %: With an Arranged OD
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.8.1+dcbbed4")]
		[ImplementPropertyType("overInterestFreeLimitUnarrangedOverdraftRateWith")]
		public virtual decimal OverInterestFreeLimitUnarrangedOverdraftRateWith => this.Value<decimal>(_publishedValueFallback, "overInterestFreeLimitUnarrangedOverdraftRateWith");

		///<summary>
		/// Over Interest Free Limit - Unarranged Overdraft Rate %: Without an Arranged OD
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.8.1+dcbbed4")]
		[ImplementPropertyType("overInterestFreeLimitUnarrangedOverdraftRateWithout")]
		public virtual decimal OverInterestFreeLimitUnarrangedOverdraftRateWithout => this.Value<decimal>(_publishedValueFallback, "overInterestFreeLimitUnarrangedOverdraftRateWithout");

		///<summary>
		/// Over Interest Info
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.8.1+dcbbed4")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("overInterestInfo")]
		public virtual string OverInterestInfo => this.Value<string>(_publishedValueFallback, "overInterestInfo");

		///<summary>
		/// Surcharge GB: Only used when user manually enters Arranged Overdraft Interest Rate
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.8.1+dcbbed4")]
		[ImplementPropertyType("surchargeGB")]
		public virtual decimal SurchargeGB => this.Value<decimal>(_publishedValueFallback, "surchargeGB");

		///<summary>
		/// Surcharge NI: Only used when user manually enters Arranged Overdraft Interest Rate
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.8.1+dcbbed4")]
		[ImplementPropertyType("surchargeNI")]
		public virtual decimal SurchargeNI => this.Value<decimal>(_publishedValueFallback, "surchargeNI");

		///<summary>
		/// Listing Image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.8.1+dcbbed4")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("listingImage")]
		public virtual global::Umbraco.Cms.Core.Models.PublishedContent.IPublishedContent ListingImage => global::BOI.Umbraco.Models.ListingMixin.GetListingImage(this, _publishedValueFallback);

		///<summary>
		/// Listing Summary
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.8.1+dcbbed4")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("listingSummary")]
		public virtual string ListingSummary => global::BOI.Umbraco.Models.ListingMixin.GetListingSummary(this, _publishedValueFallback);

		///<summary>
		/// Hide main navigation
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.8.1+dcbbed4")]
		[ImplementPropertyType("hideMainNavigation")]
		public virtual bool HideMainNavigation => global::BOI.Umbraco.Models.NavigationMixin.GetHideMainNavigation(this, _publishedValueFallback);

		///<summary>
		/// Mobile nav icon
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.8.1+dcbbed4")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("mobileNavIcon")]
		public virtual global::System.Collections.Generic.IEnumerable<global::Umbraco.Cms.Core.Models.PublishedContent.IPublishedContent> MobileNavIcon => global::BOI.Umbraco.Models.NavigationMixin.GetMobileNavIcon(this, _publishedValueFallback);

		///<summary>
		/// Internal redirect: Will load the selected page’s content transparently without performing any URL redirection. This essentially performs a rewrite. Use with caution
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.8.1+dcbbed4")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("umbracoInternalRedirectId")]
		public virtual global::Umbraco.Cms.Core.Models.PublishedContent.IPublishedContent UmbracoInternalRedirectId => global::BOI.Umbraco.Models.NavigationMixin.GetUmbracoInternalRedirectId(this, _publishedValueFallback);

		///<summary>
		/// Redirect to node: Redirect this page to another node on the site. USE WITH CAUTION
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.8.1+dcbbed4")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("umbracoRedirect")]
		public virtual global::Umbraco.Cms.Core.Models.PublishedContent.IPublishedContent UmbracoRedirect => global::BOI.Umbraco.Models.NavigationMixin.GetUmbracoRedirect(this, _publishedValueFallback);

		///<summary>
		/// Page Settings
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.8.1+dcbbed4")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("pageSettings")]
		public virtual global::System.Collections.Generic.IEnumerable<global::Umbraco.Cms.Core.Models.PublishedContent.IPublishedElement> PageSettings => global::BOI.Umbraco.Models.PageSettingsMixin.GetPageSettings(this, _publishedValueFallback);

		///<summary>
		/// Exclude from search
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.8.1+dcbbed4")]
		[ImplementPropertyType("excludeFromSearch")]
		public virtual bool ExcludeFromSearch => global::BOI.Umbraco.Models.SearchMixin.GetExcludeFromSearch(this, _publishedValueFallback);

		///<summary>
		/// Search description: Short description to show on the search result for this page
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.8.1+dcbbed4")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("searchDescription")]
		public virtual string SearchDescription => global::BOI.Umbraco.Models.SearchMixin.GetSearchDescription(this, _publishedValueFallback);

		///<summary>
		/// Search keywords: Enter a comma separated list of keywords to use as part of the site search.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.8.1+dcbbed4")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("searchKeywords")]
		public virtual string SearchKeywords => global::BOI.Umbraco.Models.SearchMixin.GetSearchKeywords(this, _publishedValueFallback);

		///<summary>
		/// Search Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.8.1+dcbbed4")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("searchTitle")]
		public virtual string SearchTitle => global::BOI.Umbraco.Models.SearchMixin.GetSearchTitle(this, _publishedValueFallback);
	}
}
