//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder.Embedded v13.4.1+d72fc5c
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Linq.Expressions;
using Umbraco.Cms.Core.Models.PublishedContent;
using Umbraco.Cms.Core.PublishedCache;
using Umbraco.Cms.Infrastructure.ModelsBuilder;
using Umbraco.Cms.Core;
using Umbraco.Extensions;

namespace BOI.Umbraco.Models
{
	/// <summary>Overdraft Rate</summary>
	[PublishedModel("overdraftRate")]
	public partial class OverdraftRate : PublishedElementModel
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.4.1+d72fc5c")]
		public new const string ModelTypeAlias = "overdraftRate";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.4.1+d72fc5c")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.4.1+d72fc5c")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public new static IPublishedContentType GetModelContentType(IPublishedSnapshotAccessor publishedSnapshotAccessor)
			=> PublishedModelUtility.GetModelContentType(publishedSnapshotAccessor, ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.4.1+d72fc5c")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(IPublishedSnapshotAccessor publishedSnapshotAccessor, Expression<Func<OverdraftRate, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(publishedSnapshotAccessor), selector);
#pragma warning restore 0109

		private IPublishedValueFallback _publishedValueFallback;

		// ctor
		public OverdraftRate(IPublishedElement content, IPublishedValueFallback publishedValueFallback)
			: base(content, publishedValueFallback)
		{
			_publishedValueFallback = publishedValueFallback;
		}

		// properties

		///<summary>
		/// Account Name: This is what will appear in the Account Type dropdown on the Calculator page
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.4.1+d72fc5c")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("accountName")]
		public virtual string AccountName => this.Value<string>(_publishedValueFallback, "accountName");

		///<summary>
		/// Arranged Overdraft Rate %
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.4.1+d72fc5c")]
		[ImplementPropertyType("arrangedOverdraftRate")]
		public virtual decimal ArrangedOverdraftRate => this.Value<decimal>(_publishedValueFallback, "arrangedOverdraftRate");

		///<summary>
		/// Arranged Overdraft Rate EAR %
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.4.1+d72fc5c")]
		[ImplementPropertyType("arrangedOverdraftRateEAR")]
		public virtual decimal ArrangedOverdraftRateEar => this.Value<decimal>(_publishedValueFallback, "arrangedOverdraftRateEAR");

		///<summary>
		/// Exclude Surcharges: Selecting true on this field will prevent a Surcharge and Minimum Surcharge from being applied to the product.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.4.1+d72fc5c")]
		[ImplementPropertyType("excludeSurcharges")]
		public virtual bool ExcludeSurcharges => this.Value<bool>(_publishedValueFallback, "excludeSurcharges");

		///<summary>
		/// Hide Arranged Overdraft: When checked, when this Account Type is selected, the Arranged Overdraft field will be hidden on the Calculator
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.4.1+d72fc5c")]
		[ImplementPropertyType("hideArrangedOverdraft")]
		public virtual bool HideArrangedOverdraft => this.Value<bool>(_publishedValueFallback, "hideArrangedOverdraft");

		///<summary>
		/// Jurisdiction: GB or NI
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.4.1+d72fc5c")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("jurisdiction")]
		public virtual string Jurisdiction => this.Value<string>(_publishedValueFallback, "jurisdiction");

		///<summary>
		/// Show Arranged Overdraft Interest Rate: When checked, when this Account Type is selected, the Arranged Overdraft Interest Rate field will show on the Calculator
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.4.1+d72fc5c")]
		[ImplementPropertyType("showArrangedOverdraftInterestRate")]
		public virtual bool ShowArrangedOverdraftInterestRate => this.Value<bool>(_publishedValueFallback, "showArrangedOverdraftInterestRate");

		///<summary>
		/// Show Course Length: When checked, when this Account Type is selected, the Course Length field will show on the Calculator
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.4.1+d72fc5c")]
		[ImplementPropertyType("showCourseLength")]
		public virtual bool ShowCourseLength => this.Value<bool>(_publishedValueFallback, "showCourseLength");

		///<summary>
		/// Unarranged Overdraft Rate EAR %: With an Arranged OD
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.4.1+d72fc5c")]
		[ImplementPropertyType("unarrangedOverdraftRateEARWith")]
		public virtual decimal UnarrangedOverdraftRateEarwith => this.Value<decimal>(_publishedValueFallback, "unarrangedOverdraftRateEARWith");

		///<summary>
		/// Unarranged Overdraft Rate EAR %: Without an Arranged OD
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.4.1+d72fc5c")]
		[ImplementPropertyType("unarrangedOverdraftRateEARWithout")]
		public virtual decimal UnarrangedOverdraftRateEarwithout => this.Value<decimal>(_publishedValueFallback, "unarrangedOverdraftRateEARWithout");

		///<summary>
		/// Unarranged Overdraft Rate %: With an Arranged OD
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.4.1+d72fc5c")]
		[ImplementPropertyType("unarrangedOverdraftRateWith")]
		public virtual decimal UnarrangedOverdraftRateWith => this.Value<decimal>(_publishedValueFallback, "unarrangedOverdraftRateWith");

		///<summary>
		/// Unarranged Overdraft Rate %: Without an Arranged OD
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.4.1+d72fc5c")]
		[ImplementPropertyType("unarrangedOverdraftRateWithout")]
		public virtual decimal UnarrangedOverdraftRateWithout => this.Value<decimal>(_publishedValueFallback, "unarrangedOverdraftRateWithout");
	}
}
