//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder.Embedded v13.8.1+dcbbed4
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Linq.Expressions;
using Umbraco.Cms.Core.Models.PublishedContent;
using Umbraco.Cms.Core.PublishedCache;
using Umbraco.Cms.Infrastructure.ModelsBuilder;
using Umbraco.Cms.Core;
using Umbraco.Extensions;

namespace BOI.Umbraco.Models
{
	/// <summary>Site Root</summary>
	[PublishedModel("siteRoot")]
	public partial class SiteRoot : PublishedContentModel, IFooterMixin
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.8.1+dcbbed4")]
		public new const string ModelTypeAlias = "siteRoot";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.8.1+dcbbed4")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.8.1+dcbbed4")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public new static IPublishedContentType GetModelContentType(IPublishedSnapshotAccessor publishedSnapshotAccessor)
			=> PublishedModelUtility.GetModelContentType(publishedSnapshotAccessor, ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.8.1+dcbbed4")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(IPublishedSnapshotAccessor publishedSnapshotAccessor, Expression<Func<SiteRoot, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(publishedSnapshotAccessor), selector);
#pragma warning restore 0109

		private IPublishedValueFallback _publishedValueFallback;

		// ctor
		public SiteRoot(IPublishedContent content, IPublishedValueFallback publishedValueFallback)
			: base(content, publishedValueFallback)
		{
			_publishedValueFallback = publishedValueFallback;
		}

		// properties

		///<summary>
		/// Contact Us Link
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.8.1+dcbbed4")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("contactUsLink")]
		public virtual global::Umbraco.Cms.Core.Models.Link ContactUsLink => this.Value<global::Umbraco.Cms.Core.Models.Link>(_publishedValueFallback, "contactUsLink");

		///<summary>
		/// Default Social Sharing Image: Minimum size: 600×315px
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.8.1+dcbbed4")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("defaultSocialSharingImage")]
		public virtual global::Umbraco.Cms.Core.Models.PublishedContent.IPublishedContent DefaultSocialSharingImage => this.Value<global::Umbraco.Cms.Core.Models.PublishedContent.IPublishedContent>(_publishedValueFallback, "defaultSocialSharingImage");

		///<summary>
		/// Disallow Robots
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.8.1+dcbbed4")]
		[ImplementPropertyType("disallowRobots")]
		public virtual bool DisallowRobots => this.Value<bool>(_publishedValueFallback, "disallowRobots");

		///<summary>
		/// 404 Error page
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.8.1+dcbbed4")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("errorPage404")]
		public virtual global::Umbraco.Cms.Core.Models.PublishedContent.IPublishedContent ErrorPage404 => this.Value<global::Umbraco.Cms.Core.Models.PublishedContent.IPublishedContent>(_publishedValueFallback, "errorPage404");

		///<summary>
		/// 500 Error page
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.8.1+dcbbed4")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("errorPage500")]
		public virtual global::Umbraco.Cms.Core.Models.PublishedContent.IPublishedContent ErrorPage500 => this.Value<global::Umbraco.Cms.Core.Models.PublishedContent.IPublishedContent>(_publishedValueFallback, "errorPage500");

		///<summary>
		/// Global Contact CTA: This link will be used for the BDM CTA, unless the item being viewed has a specific one chosen.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.8.1+dcbbed4")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("globalBDMCTA")]
		public virtual global::Umbraco.Cms.Core.Models.Link GlobalBdmcta => this.Value<global::Umbraco.Cms.Core.Models.Link>(_publishedValueFallback, "globalBDMCTA");

		///<summary>
		/// Global Hero Pod Picker: The hero pod fallbacks should be selected here.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.8.1+dcbbed4")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("globalHeroPodPicker")]
		public virtual global::System.Collections.Generic.IEnumerable<global::Umbraco.Cms.Core.Models.PublishedContent.IPublishedContent> GlobalHeroPodPicker => this.Value<global::System.Collections.Generic.IEnumerable<global::Umbraco.Cms.Core.Models.PublishedContent.IPublishedContent>>(_publishedValueFallback, "globalHeroPodPicker");

		///<summary>
		/// Global Product CTA: This link will be used for the product CTA, unless the item being viewed has a specific one chosen.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.8.1+dcbbed4")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("globalProductCTA")]
		public virtual global::Umbraco.Cms.Core.Models.Link GlobalProductCta => this.Value<global::Umbraco.Cms.Core.Models.Link>(_publishedValueFallback, "globalProductCTA");

		///<summary>
		/// Hide Print PDF Link
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.8.1+dcbbed4")]
		[ImplementPropertyType("hidePrintPDFLink")]
		public virtual bool HidePrintPdflink => this.Value<bool>(_publishedValueFallback, "hidePrintPDFLink");

		///<summary>
		/// LinkedIn Link
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.8.1+dcbbed4")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("linkedInLink")]
		public virtual global::Umbraco.Cms.Core.Models.Link LinkedInLink => this.Value<global::Umbraco.Cms.Core.Models.Link>(_publishedValueFallback, "linkedInLink");

		///<summary>
		/// Login Link
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.8.1+dcbbed4")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("loginLink")]
		public virtual global::Umbraco.Cms.Core.Models.Link LoginLink => this.Value<global::Umbraco.Cms.Core.Models.Link>(_publishedValueFallback, "loginLink");

		///<summary>
		/// Main Navigation
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.8.1+dcbbed4")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("mainNavigation")]
		public virtual global::Umbraco.Cms.Core.Models.Blocks.BlockListModel MainNavigation => this.Value<global::Umbraco.Cms.Core.Models.Blocks.BlockListModel>(_publishedValueFallback, "mainNavigation");

		///<summary>
		/// Navigation
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.8.1+dcbbed4")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("navigation")]
		public virtual global::System.Collections.Generic.IEnumerable<global::Our.Umbraco.Meganav.Models.IMeganavItem> Navigation => this.Value<global::System.Collections.Generic.IEnumerable<global::Our.Umbraco.Meganav.Models.IMeganavItem>>(_publishedValueFallback, "navigation");

		///<summary>
		/// Notifications
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.8.1+dcbbed4")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("notifications")]
		public virtual global::Umbraco.Cms.Core.Models.Blocks.BlockListModel Notifications => this.Value<global::Umbraco.Cms.Core.Models.Blocks.BlockListModel>(_publishedValueFallback, "notifications");

		///<summary>
		/// Pop Up Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.8.1+dcbbed4")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("popUpText")]
		public virtual global::Umbraco.Cms.Core.Strings.IHtmlEncodedString PopUpText => this.Value<global::Umbraco.Cms.Core.Strings.IHtmlEncodedString>(_publishedValueFallback, "popUpText");

		///<summary>
		/// Pop Up Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.8.1+dcbbed4")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("popUpTitle")]
		public virtual string PopUpTitle => this.Value<string>(_publishedValueFallback, "popUpTitle");

		///<summary>
		/// Register Link
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.8.1+dcbbed4")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("registerLink")]
		public virtual global::Umbraco.Cms.Core.Models.Link RegisterLink => this.Value<global::Umbraco.Cms.Core.Models.Link>(_publishedValueFallback, "registerLink");

		///<summary>
		/// Robots meta
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.8.1+dcbbed4")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("robotsMeta")]
		public virtual string RobotsMeta => this.Value<string>(_publishedValueFallback, "robotsMeta");

		///<summary>
		/// Search Results Link
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.8.1+dcbbed4")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("searchResultsLink")]
		public virtual global::Umbraco.Cms.Core.Models.Link SearchResultsLink => this.Value<global::Umbraco.Cms.Core.Models.Link>(_publishedValueFallback, "searchResultsLink");

		///<summary>
		/// Website Name: Displayed when shared on social media
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.8.1+dcbbed4")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("siteName")]
		public virtual string SiteName => this.Value<string>(_publishedValueFallback, "siteName");

		///<summary>
		/// Settings
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.8.1+dcbbed4")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("siteSettings")]
		public virtual global::System.Collections.Generic.IEnumerable<global::BOI.Umbraco.Models.GlobalScripts> SiteSettings => this.Value<global::System.Collections.Generic.IEnumerable<global::BOI.Umbraco.Models.GlobalScripts>>(_publishedValueFallback, "siteSettings");

		///<summary>
		/// Home Page
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.8.1+dcbbed4")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("umbracoInternalRedirectId")]
		public virtual global::Umbraco.Cms.Core.Models.PublishedContent.IPublishedContent UmbracoInternalRedirectId => this.Value<global::Umbraco.Cms.Core.Models.PublishedContent.IPublishedContent>(_publishedValueFallback, "umbracoInternalRedirectId");

		///<summary>
		/// Unsupported browser text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.8.1+dcbbed4")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("unsupportedBrowserText")]
		public virtual global::Umbraco.Cms.Core.Strings.IHtmlEncodedString UnsupportedBrowserText => this.Value<global::Umbraco.Cms.Core.Strings.IHtmlEncodedString>(_publishedValueFallback, "unsupportedBrowserText");

		///<summary>
		/// Bottom Links: Select the links that will appear at the bottom of the footer
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.8.1+dcbbed4")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("bottomLinks")]
		public virtual global::System.Collections.Generic.IEnumerable<global::Umbraco.Cms.Core.Models.Link> BottomLinks => global::BOI.Umbraco.Models.FooterMixin.GetBottomLinks(this, _publishedValueFallback);

		///<summary>
		/// Column 1 Heading Link: Please enter the heading that will appear above the quick links in column 1. If nothing is selected this column will not display
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.8.1+dcbbed4")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("column1HeadingLink")]
		public virtual global::Umbraco.Cms.Core.Models.Link Column1HeadingLink => global::BOI.Umbraco.Models.FooterMixin.GetColumn1HeadingLink(this, _publishedValueFallback);

		///<summary>
		/// Column 1 Links: Select the links that will appear in the footer, in column 1
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.8.1+dcbbed4")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("column1Links")]
		public virtual global::System.Collections.Generic.IEnumerable<global::Umbraco.Cms.Core.Models.Link> Column1Links => global::BOI.Umbraco.Models.FooterMixin.GetColumn1Links(this, _publishedValueFallback);

		///<summary>
		/// Column 2 Heading Link: Please enter the heading that will appear above the quick links in column 2. If nothing is selected this column will not display
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.8.1+dcbbed4")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("column2HeadingLink")]
		public virtual global::Umbraco.Cms.Core.Models.Link Column2HeadingLink => global::BOI.Umbraco.Models.FooterMixin.GetColumn2HeadingLink(this, _publishedValueFallback);

		///<summary>
		/// Column 2 Links: Select the links that will appear in the footer, in column 2
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.8.1+dcbbed4")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("column2Links")]
		public virtual global::System.Collections.Generic.IEnumerable<global::Umbraco.Cms.Core.Models.Link> Column2Links => global::BOI.Umbraco.Models.FooterMixin.GetColumn2Links(this, _publishedValueFallback);

		///<summary>
		/// Column 3 Heading Link: Please enter the heading that will appear above the quick links in column 3. If nothing is selected this column will not display
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.8.1+dcbbed4")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("column3HeadingLink")]
		public virtual global::Umbraco.Cms.Core.Models.Link Column3HeadingLink => global::BOI.Umbraco.Models.FooterMixin.GetColumn3HeadingLink(this, _publishedValueFallback);

		///<summary>
		/// Column 3 Links: Select the links that will appear in the footer , in column 3
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.8.1+dcbbed4")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("column3Links")]
		public virtual global::System.Collections.Generic.IEnumerable<global::Umbraco.Cms.Core.Models.Link> Column3Links => global::BOI.Umbraco.Models.FooterMixin.GetColumn3Links(this, _publishedValueFallback);

		///<summary>
		/// Column 4 Heading Link: Please enter the heading that will appear above the quick links in column 4. If nothing is selected this column will not display
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.8.1+dcbbed4")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("column4HeadingLink")]
		public virtual global::Umbraco.Cms.Core.Models.Link Column4HeadingLink => global::BOI.Umbraco.Models.FooterMixin.GetColumn4HeadingLink(this, _publishedValueFallback);

		///<summary>
		/// Column 4 Links: Select the links that will appear in the footer , in column 4
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.8.1+dcbbed4")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("column4Links")]
		public virtual global::System.Collections.Generic.IEnumerable<global::Umbraco.Cms.Core.Models.Link> Column4Links => global::BOI.Umbraco.Models.FooterMixin.GetColumn4Links(this, _publishedValueFallback);

		///<summary>
		/// Copyright Link: Please select the copyright link
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.8.1+dcbbed4")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("copyrightLink")]
		public virtual global::Umbraco.Cms.Core.Models.Link CopyrightLink => global::BOI.Umbraco.Models.FooterMixin.GetCopyrightLink(this, _publishedValueFallback);

		///<summary>
		/// Footer Text: Please enter the text that will appear in the footer
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.8.1+dcbbed4")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("footerText")]
		public virtual global::Umbraco.Cms.Core.Strings.IHtmlEncodedString FooterText => global::BOI.Umbraco.Models.FooterMixin.GetFooterText(this, _publishedValueFallback);
	}
}
