//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder.Embedded v13.4.1+d72fc5c
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Linq.Expressions;
using Umbraco.Cms.Core.Models.PublishedContent;
using Umbraco.Cms.Core.PublishedCache;
using Umbraco.Cms.Infrastructure.ModelsBuilder;
using Umbraco.Cms.Core;
using Umbraco.Extensions;

namespace BOI.Umbraco.Models
{
	/// <summary>Solicitor Landing</summary>
	[PublishedModel("solicitorLanding")]
	public partial class SolicitorLanding : PublishedContentModel, IHeroMixin, IListingMixin, INavigationMixin, IPageSettingsMixin, IPodsMixin, ISearchMixin
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.4.1+d72fc5c")]
		public new const string ModelTypeAlias = "solicitorLanding";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.4.1+d72fc5c")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.4.1+d72fc5c")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public new static IPublishedContentType GetModelContentType(IPublishedSnapshotAccessor publishedSnapshotAccessor)
			=> PublishedModelUtility.GetModelContentType(publishedSnapshotAccessor, ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.4.1+d72fc5c")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(IPublishedSnapshotAccessor publishedSnapshotAccessor, Expression<Func<SolicitorLanding, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(publishedSnapshotAccessor), selector);
#pragma warning restore 0109

		private IPublishedValueFallback _publishedValueFallback;

		// ctor
		public SolicitorLanding(IPublishedContent content, IPublishedValueFallback publishedValueFallback)
			: base(content, publishedValueFallback)
		{
			_publishedValueFallback = publishedValueFallback;
		}

		// properties

		///<summary>
		/// Content
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.4.1+d72fc5c")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("content")]
		public virtual global::Umbraco.Cms.Core.Models.Blocks.BlockListModel Content => this.Value<global::Umbraco.Cms.Core.Models.Blocks.BlockListModel>(_publishedValueFallback, "content");

		///<summary>
		/// Form Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.4.1+d72fc5c")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("formTitle")]
		public virtual string FormTitle => this.Value<string>(_publishedValueFallback, "formTitle");

		///<summary>
		/// No Results Message
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.4.1+d72fc5c")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("noResultsMessage")]
		public virtual string NoResultsMessage => this.Value<string>(_publishedValueFallback, "noResultsMessage");

		///<summary>
		/// Search Name Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.4.1+d72fc5c")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("searchNameText")]
		public virtual string SearchNameText => this.Value<string>(_publishedValueFallback, "searchNameText");

		///<summary>
		/// Search Postcode Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.4.1+d72fc5c")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("searchPostcodeText")]
		public virtual string SearchPostcodeText => this.Value<string>(_publishedValueFallback, "searchPostcodeText");

		///<summary>
		/// Background Colour: This field will allow you to choose the colour of the background elements, in the hero banner.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.4.1+d72fc5c")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("backgroundColour")]
		public virtual global::Umbraco.Cms.Core.PropertyEditors.ValueConverters.ColorPickerValueConverter.PickedColor BackgroundColour => global::BOI.Umbraco.Models.HeroMixin.GetBackgroundColour(this, _publishedValueFallback);

		///<summary>
		/// Background Image: This is the image that will appear on the background of the hero area.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.4.1+d72fc5c")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("backgroundImage")]
		public virtual global::Umbraco.Cms.Core.Models.PublishedContent.IPublishedContent BackgroundImage => global::BOI.Umbraco.Models.HeroMixin.GetBackgroundImage(this, _publishedValueFallback);

		///<summary>
		/// BDM Finder CTA: A page specific BDM Finder link can be chosen here. If nothing is selected this will fall back to the global setting.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.4.1+d72fc5c")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("bDMFinderCta")]
		public virtual global::Umbraco.Cms.Core.Models.Link BDmfinderCta => global::BOI.Umbraco.Models.HeroMixin.GetBDmfinderCta(this, _publishedValueFallback);

		///<summary>
		/// CTA: The CTA (Call To Action) should be used to direct the user to a specific page.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.4.1+d72fc5c")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("cTA")]
		public virtual global::Umbraco.Cms.Core.Models.Link CTA => global::BOI.Umbraco.Models.HeroMixin.GetCTA(this, _publishedValueFallback);

		///<summary>
		/// Hero Pod Picker: This can be used to pick the pod for the hero item.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.4.1+d72fc5c")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("heroPodPicker")]
		public virtual global::System.Collections.Generic.IEnumerable<global::Umbraco.Cms.Core.Models.PublishedContent.IPublishedContent> HeroPodPicker => global::BOI.Umbraco.Models.HeroMixin.GetHeroPodPicker(this, _publishedValueFallback);

		///<summary>
		/// Hide BDM Finder CTA: Tick this checkbox to hide the BDM Finder CTA
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.4.1+d72fc5c")]
		[ImplementPropertyType("hideBDMFinder")]
		public virtual bool HideBdmfinder => global::BOI.Umbraco.Models.HeroMixin.GetHideBdmfinder(this, _publishedValueFallback);

		///<summary>
		/// Hide Product CTA: Tick this checkbox to hide the Product CTA
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.4.1+d72fc5c")]
		[ImplementPropertyType("hideProductCTA")]
		public virtual bool HideProductCta => global::BOI.Umbraco.Models.HeroMixin.GetHideProductCta(this, _publishedValueFallback);

		///<summary>
		/// Product CTA: A page specific Product CTA can be chosen here. If nothing is selected this will fall back to the global setting.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.4.1+d72fc5c")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("productCTA")]
		public virtual global::Umbraco.Cms.Core.Models.Link ProductCta => global::BOI.Umbraco.Models.HeroMixin.GetProductCta(this, _publishedValueFallback);

		///<summary>
		/// Supporting Text: The supporting text that will appear underneath the title in the hero. If left blank this will not show on the hero area
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.4.1+d72fc5c")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("supportingText")]
		public virtual global::Umbraco.Cms.Core.Strings.IHtmlEncodedString SupportingText => global::BOI.Umbraco.Models.HeroMixin.GetSupportingText(this, _publishedValueFallback);

		///<summary>
		/// Title: The title that will appear on the hero area
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.4.1+d72fc5c")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("title")]
		public virtual string Title => global::BOI.Umbraco.Models.HeroMixin.GetTitle(this, _publishedValueFallback);

		///<summary>
		/// Listing Image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.4.1+d72fc5c")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("listingImage")]
		public virtual global::Umbraco.Cms.Core.Models.PublishedContent.IPublishedContent ListingImage => global::BOI.Umbraco.Models.ListingMixin.GetListingImage(this, _publishedValueFallback);

		///<summary>
		/// Listing Summary
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.4.1+d72fc5c")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("listingSummary")]
		public virtual string ListingSummary => global::BOI.Umbraco.Models.ListingMixin.GetListingSummary(this, _publishedValueFallback);

		///<summary>
		/// Hide main navigation
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.4.1+d72fc5c")]
		[ImplementPropertyType("hideMainNavigation")]
		public virtual bool HideMainNavigation => global::BOI.Umbraco.Models.NavigationMixin.GetHideMainNavigation(this, _publishedValueFallback);

		///<summary>
		/// Internal redirect: Will load the selected page’s content transparently without performing any URL redirection. This essentially performs a rewrite. Use with caution
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.4.1+d72fc5c")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("umbracoInternalRedirectId")]
		public virtual global::Umbraco.Cms.Core.Models.PublishedContent.IPublishedContent UmbracoInternalRedirectId => global::BOI.Umbraco.Models.NavigationMixin.GetUmbracoInternalRedirectId(this, _publishedValueFallback);

		///<summary>
		/// Redirect to node: Redirect this page to another node on the site. USE WITH CAUTION
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.4.1+d72fc5c")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("umbracoRedirect")]
		public virtual global::Umbraco.Cms.Core.Models.PublishedContent.IPublishedContent UmbracoRedirect => global::BOI.Umbraco.Models.NavigationMixin.GetUmbracoRedirect(this, _publishedValueFallback);

		///<summary>
		/// Page Settings
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.4.1+d72fc5c")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("pageSettings")]
		public virtual global::System.Collections.Generic.IEnumerable<global::Umbraco.Cms.Core.Models.PublishedContent.IPublishedElement> PageSettings => global::BOI.Umbraco.Models.PageSettingsMixin.GetPageSettings(this, _publishedValueFallback);

		///<summary>
		/// Pods
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.4.1+d72fc5c")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("pods")]
		public virtual global::System.Collections.Generic.IEnumerable<global::Umbraco.Cms.Core.Models.PublishedContent.IPublishedContent> Pods => global::BOI.Umbraco.Models.PodsMixin.GetPods(this, _publishedValueFallback);

		///<summary>
		/// Exclude from search
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.4.1+d72fc5c")]
		[ImplementPropertyType("excludeFromSearch")]
		public virtual bool ExcludeFromSearch => global::BOI.Umbraco.Models.SearchMixin.GetExcludeFromSearch(this, _publishedValueFallback);

		///<summary>
		/// Search description: Short description to show on the search result for this page
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.4.1+d72fc5c")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("searchDescription")]
		public virtual string SearchDescription => global::BOI.Umbraco.Models.SearchMixin.GetSearchDescription(this, _publishedValueFallback);

		///<summary>
		/// Search keywords: Enter a comma separated list of keywords to use as part of the site search.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.4.1+d72fc5c")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("searchKeywords")]
		public virtual string SearchKeywords => global::BOI.Umbraco.Models.SearchMixin.GetSearchKeywords(this, _publishedValueFallback);

		///<summary>
		/// Search Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.4.1+d72fc5c")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("searchTitle")]
		public virtual string SearchTitle => global::BOI.Umbraco.Models.SearchMixin.GetSearchTitle(this, _publishedValueFallback);
	}
}
