name: Build and Deploy BOI4I

on:
  push:
    branches:
      - release/test
      - release/staging

env:
  DOTNET_VERSION: '8.0.x'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
        
    - name: Build and Publish
      run: |
        dotnet restore
        dotnet build --configuration Release
        dotnet test --configuration Release
        dotnet publish BOI.Web/BOI.Web.csproj \
          --configuration Release \
          --output ./publish
          
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: boi4i-app-${{ github.ref_name == 'release/test' && 'release-test' || github.ref_name == 'release/staging' && 'release-staging' || github.ref_name }}
        path: ./publish/

  deploy:
    needs: build
    runs-on: [self-hosted, windows]
    environment: ${{ github.ref_name }}
    env:
      ENV_SUFFIX: ${{ github.ref_name == 'release/test' && 'BOI4I_TEST' || github.ref_name == 'release/staging' && 'BOI4I_STAGING' || 'BOI4I_PROD' }}
    
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: boi4i-app-${{ github.ref_name == 'release/test' && 'release-test' || github.ref_name == 'release/staging' && 'release-staging' || github.ref_name }}
        path: ./publish/

    - name: Debug environment
      run: |
        echo "Branch: ${{ github.ref_name }}"
        echo "Environment Suffix: ${{ env.ENV_SUFFIX }}"
        echo "Expected secrets:"
        echo "  DEPLOY_HOST_${{ env.ENV_SUFFIX }}"
        echo "  DEPLOY_USER_${{ env.ENV_SUFFIX }}"
        echo "  DEPLOY_PASSWORD_${{ env.ENV_SUFFIX }}"
        echo "  DEPLOY_PATH_${{ env.ENV_SUFFIX }}"
        echo "  APP_POOL_${{ env.ENV_SUFFIX }}"

    - name: Create deployment package
      run: |
        Compress-Archive -Path "./publish/*" -DestinationPath "./deployment-package.zip" -Force

    - name: Deploy application
      run: |
        
        try {
          # Copy the deployment package to the remote server
          Copy-Item -Path "./deployment-package.zip" -Destination "C:\Temp\deployment-package.zip" 
          
          # Execute deployment script on remote server
          Write-Host "Executing deployment on remote server..."
          Invoke-Command -ScriptBlock {
            param($DeployPath, $AppPool, $RefName)
            
            # Import required modules
            Import-Module WebAdministration
            
            # Enable long path support for this PowerShell session
            try {
              $registryPath = "HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem"
              $longPathEnabled = Get-ItemProperty -Path $registryPath -Name "LongPathsEnabled" -ErrorAction SilentlyContinue
              if ($longPathEnabled -and $longPathEnabled.LongPathsEnabled -eq 1) {
                Write-Host "Long path support is already enabled"
              } else {
                Write-Host "Long path support is not enabled - this may cause issues with very long filenames"
              }
            } catch {
              Write-Host "Could not check long path support status: $($_.Exception.Message)"
            }
            
            # Stop the application pool
            Write-Host "Stopping application pool: $AppPool"
            try {
              Stop-WebAppPool -Name $AppPool -ErrorAction Stop
              Write-Host "Application pool stopped successfully"
            } catch {
              if ($_.Exception.Message -like "*already stopped*") {
                Write-Host "Application pool is already stopped"
              } else {
                Write-Host "Warning: Could not stop application pool: $($_.Exception.Message)"
              }
            }
            
            # Stop the website
            Write-Host "Stopping website..."
            try {
              $siteName = (Get-WebAppPoolState -Name $AppPool).ApplicationPool
              $sites = Get-Website | Where-Object { $_.ApplicationPool -eq $AppPool }
              foreach ($site in $sites) {
                Write-Host "Stopping website: $($site.Name)"
                Stop-Website -Name $site.Name -ErrorAction Stop
                Write-Host "Website '$($site.Name)' stopped successfully"
              }
            } catch {
              Write-Host "Warning: Could not stop website: $($_.Exception.Message)"
            }
            
            # Wait for application to fully stop
            Write-Host "Waiting 5 seconds for application to fully stop..."
            Start-Sleep -Seconds 5
            
            # Create backup only for staging environment
            if (Test-Path $DeployPath) {
              if ($RefName -like "*staging*") {
                $backupPath = "C:\Backups\$RefName-$(Get-Date -Format 'yyyyMMdd-HHmmss')"
                Write-Host "Creating backup at: $backupPath"
                New-Item -ItemType Directory -Path "C:\Backups" -Force | Out-Null
                Copy-Item -Path $DeployPath -Destination $backupPath -Recurse -Force
              } else {
                Write-Host "Skipping backup for test environment"
              }
              Get-ChildItem -Path $DeployPath -Recurse | Remove-Item -Force -Recurse
            } else {
              Write-Host "Creating deployment directory: $DeployPath"
              New-Item -ItemType Directory -Path $DeployPath -Force | Out-Null
            }
            
            # Extract deployment package
            Write-Host "Extracting deployment package..."
            Expand-Archive -Path "C:\Temp\deployment-package.zip" -DestinationPath $DeployPath -Force
            Remove-Item "C:\Temp\deployment-package.zip" -Force
            
            # Update web.config with environment-specific settings based on branch
            $webConfigPath = Join-Path $DeployPath "web.config"
            if (Test-Path $webConfigPath) {
              Write-Host "Updating web.config environment settings for branch: $RefName"
              
              # Determine environment based on branch name
              $environment = switch ($RefName.ToLower()) {
                { $_ -like "*test*" } { "Test" }
                { $_ -like "*staging*" } { "Production" }
              }
              
              Write-Host "Setting ASPNETCORE_ENVIRONMENT to: $environment"
              
              # Load and update web.config
              [xml]$webConfig = Get-Content $webConfigPath
              
              # Debug: Show XML structure
              Write-Host "Debug: XML loaded successfully"
              Write-Host "Debug: Configuration exists: $($webConfig.configuration -ne $null)"
              Write-Host "Debug: Location exists: $($webConfig.configuration.location -ne $null)"
              Write-Host "Debug: system.webServer exists: $($webConfig.configuration.location.'system.webServer' -ne $null)"
              Write-Host "Debug: aspNetCore exists: $($webConfig.configuration.location.'system.webServer'.aspNetCore -ne $null)"
              Write-Host "Debug: environmentVariables exists: $($webConfig.configuration.location.'system.webServer'.aspNetCore.environmentVariables -ne $null)"
              
              $environmentVariables = $webConfig.configuration.location.'system.webServer'.aspNetCore.environmentVariables.environmentVariable
              Write-Host "Debug: Environment variables count: $($environmentVariables.Count)"
              
              if ($environmentVariables) {
                Write-Host "Debug: Available environment variables:"
                foreach ($envVar in $environmentVariables) {
                  Write-Host "  - Name: '$($envVar.name)', Value: '$($envVar.value)'"
                }
              }
              
              $targetVariable = $environmentVariables | Where-Object { $_.name -eq "ASPNETCORE_ENVIRONMENT" }
              
              Write-Host "Target variable found: $($targetVariable -ne $null)"
              if ($targetVariable) {
                Write-Host "Target variable name: $($targetVariable.name)"
                Write-Host "Target variable current value: $($targetVariable.value)"
              }
              
              if ($targetVariable) {
                $oldValue = $targetVariable.value
                $targetVariable.value = $environment
                $webConfig.Save($webConfigPath)
                Write-Host "Updated ASPNETCORE_ENVIRONMENT from '$oldValue' to '$environment'"
              } else {
                Write-Host "Warning: ASPNETCORE_ENVIRONMENT variable not found in web.config"
              }
            } else {
              Write-Host "Warning: web.config not found at $webConfigPath"
            }
            
            # Start the application pool
            Write-Host "Starting application pool: $AppPool"
            try {
              Start-WebAppPool -Name $AppPool -ErrorAction Stop
              Write-Host "Application pool started successfully"
            } catch {
              Write-Host "Error starting application pool: $($_.Exception.Message)"
              throw
            }
            
            # Start the website
            Write-Host "Starting website..."
            try {
              $sites = Get-Website | Where-Object { $_.ApplicationPool -eq $AppPool }
              foreach ($site in $sites) {
                Write-Host "Starting website: $($site.Name)"
                Start-Website -Name $site.Name -ErrorAction Stop
                Write-Host "Website '$($site.Name)' started successfully"
              }
            } catch {
              Write-Host "Warning: Could not start website: $($_.Exception.Message)"
            }
            
            # Wait for application to start
            Write-Host "Waiting for application to start..."
            Start-Sleep -Seconds 15
            
            # Verify deployment
            Write-Host "Deployment completed successfully!"
          } -ArgumentList "${{ secrets[format('DEPLOY_PATH_{0}', env.ENV_SUFFIX)] }}", "${{ secrets[format('APP_POOL_{0}', env.ENV_SUFFIX)] }}", "${{ github.ref_name }}"
          
        } finally {
        }